theme: minima
title: Ashish's blog
author: Ashish
email: ashish.aggarwal2@capitalone.com  
description: > # this means to ignore newlines until "baseurl:"
This is awesome!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
